# phone_login = driver.find_element(By.XPATH, "//div[text()='Log in with phone number']")
# phone_login.click()
# print("Clicked on phone login option.")
# time.sleep(1)
# dropdown = driver.find_element(By.XPATH, "(//span[@data-icon='chevron'])[2]")
# dropdown.click()
# print("Clicked on dropdown to select country code.")
# time.sleep(1)
# country_name = driver.find_element(By.XPATH, "//div[@role='textbox']")
# country_name.send_keys("Pakistan")
# time.sleep(1)
# select_country = driver.find_element(By.XPATH, "(//div[text()='Pakistan'])[1]")
# select_country.click()
# print("Selected country code.")
# time.sleep(1)
# phone_login = driver.find_element(By.XPATH, "//input[@aria-label='Type your phone number.']")
# phone_login.send_keys("3087995995")
# print("Entered phone number.")
# time.sleep(1)
# next_button = driver.find_element(By.XPATH, "//div[text()='Next']")
# next_button.click()
# print("Clicked on next button.")
# time.sleep(5)
# code = driver.find_element(By.XPATH, "//div[contains(@aria-details,'link-device-phone-number')]")
# code_num = code.text
# print("Write this code on your WhatsApp: ", code_num)
# time.sleep(10)